### PR TITLE
More algorithms and other goodies.

### PR DESCRIPTION
**Pull request by Morwenn**
I replaced raw `for` loops by standard library algorithm from the header `<algorithm>`. While it shouldn't speed up anything, algorithms have on big advantage: they have a name. Which means that we don't have to read the whole `for` loop to guess what it's doing, the algorithm's name already conveys that. If we are lucky, they might sometimes be faster than a hand-rolled algorithm when sbtle optimizations exist.

I also used some functions from `<cctype>` to simplify some things, and had to use `std::back_inserter` from `<iterator>` in some algorithms.

### CODE REVIEW

**Comment by christopho** [comment]
I find the old syntax more readable in most cases. The std::find() and std::copy() are welcome: they are readable because they do only one thing. But I am not so sure about the std::find_if, std::any_of, std::all_of, and std::copy_if stuff. Or we should at least use functors that have a name instead of lambdas. Lambdas like this make the expression too heavy and harder to read.

**Comment by Morwenn** [comment]
The problem of functors is that they become ugly real fast when there are captures involved and really add more code especially for things that are only used once. I have to agree that the rane-based `for` loop tend to make things easier to read though. I am still waiting for the day when we can pass containers to algorithms instead of pair of iterators. I mostly proposed that pull request to showcase how it could have been done with algorithms ^^

Now... we, you do as you want :)

**Comment by christopho** [comment]
Hum, you are right about functors, let's don't use them here :)

**Comment by christopho** [comment]
Okay so I am closing the pull request.
If you want to make another one with only the std::find, std::copy and std::is_digit I will be glad to merge it.

**Pull request closed without merging**
